-- デフォルト権限の設定を削除
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM bot_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM bot_user;

-- シーケンスへの権限を削除
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM bot_user;

-- voice_text_links テーブルへの権限を削除
REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE voice_text_links FROM bot_user;
